"""Embodied systems namespace.

This package groups all robot-facing architecture under one deeper layer so the
top-level ``roboclaw`` package does not become a flat list of mixed concerns.
"""

from roboclaw.embodied.definition import (
    AssemblyBlueprint,
    AssemblyManifest,
    AssemblyRegistry,
    CapabilityFamily,
    CarrierKind,
    CameraColorMode,
    CameraConfig,
    CameraDriver,
    CameraRotation,
    CameraSensorManifest,
    DeploymentProfile,
    DeploymentRegistry,
    OpenCVCameraConfig,
    PrimitiveKind,
    RGB_CAMERA,
    RealSenseCameraConfig,
    RobotConfig,
    RobotManifest,
    RobotRegistry,
    RobotType,
    Ros2RobotConfig,
    Ros2CameraConfig,
    SO101_ROBOT,
    SensorKind,
    SensorManifest,
    SensorRegistry,
    SimulatorKind,
    SimulatorRegistry,
    TransportKind,
    compose_assemblies,
)
from roboclaw.embodied.catalog import EmbodiedCatalog, build_catalog, build_default_catalog
from roboclaw.embodied.execution import (
    ActionTrace,
    AdapterBinding,
    AdapterRegistry,
    DEFAULT_PROCEDURES,
    EmbodiedAdapter,
    ExecutionTarget,
    ProcedureDefinition,
    ProcedureKind,
    ProcedureRegistry,
    RuntimeManager,
    RuntimeSession,
    RuntimeStatus,
    RuntimeTask,
    StateSnapshot,
    TelemetryEvent,
    TelemetryKind,
)

__all__ = [
    "ActionTrace",
    "AdapterBinding",
    "AdapterRegistry",
    "EmbodiedAdapter",
    "AssemblyBlueprint",
    "AssemblyManifest",
    "AssemblyRegistry",
    "CapabilityFamily",
    "CameraColorMode",
    "CameraConfig",
    "CameraDriver",
    "CameraRotation",
    "CameraSensorManifest",
    "CarrierKind",
    "DEFAULT_PROCEDURES",
    "DeploymentProfile",
    "DeploymentRegistry",
    "EmbodiedCatalog",
    "ExecutionTarget",
    "OpenCVCameraConfig",
    "PrimitiveKind",
    "ProcedureDefinition",
    "ProcedureKind",
    "RGB_CAMERA",
    "RealSenseCameraConfig",
    "RobotConfig",
    "RobotManifest",
    "RobotRegistry",
    "RobotType",
    "Ros2RobotConfig",
    "Ros2CameraConfig",
    "RuntimeManager",
    "RuntimeSession",
    "RuntimeStatus",
    "RuntimeTask",
    "SO101_ROBOT",
    "SimulatorRegistry",
    "SensorKind",
    "SensorManifest",
    "SensorRegistry",
    "StateSnapshot",
    "SimulatorKind",
    "TelemetryEvent",
    "TelemetryKind",
    "TransportKind",
    "build_catalog",
    "build_default_catalog",
    "compose_assemblies",
]
